CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  description VARCHAR NOT NULL,
  points INT NOT NULL,
  user_id INT NOT NULL REFERENCES users (id),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  due_by TIMESTAMP WITH TIME ZONE
);
